# generated by datamodel-codegen:
#   filename:  Barcoding_oas3.yaml
#   timestamp: 2024-10-17T06:20:07+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

Field_alias = Field


class ProductBarcodeResponse(BaseModel):
    DigiKeyPartNumber: str = Field(description="The Digi-Key part number.")
    ManufacturerPartNumber: str = Field(
        None, description="The manufacturer part number."
    )
    ManufacturerName: str = Field(description="Manufacturer of the product.")
    ProductDescription: str = Field(
        None, description="Catalog description of the product."
    )
    Quantity: int = Field(description="Quantity of the product.")


class ApiValidationError(BaseModel):
    Field: str = Field_alias(None)
    Message: str = Field_alias(None)


class ApiErrorResponse(BaseModel):
    ErrorResponseVersion: str = Field(None)
    StatusCode: int = Field(None)
    ErrorMessage: str = Field(None)
    ErrorDetails: str = Field(None)
    RequestId: str = Field(None)
    ValidationErrors: Optional[List[ApiValidationError]] = Field(None)


class Product2DBarcodeResponse(BaseModel):
    DigiKeyPartNumber: str = Field(description="The Digi-Key part number.")
    ManufacturerPartNumber: str | None = Field(
        None, description="The manufacturer part number."
    )
    ManufacturerName: str = Field(description="Manufacturer of the product.")
    ProductDescription: str | None = Field(
        None, description="Catalog description of the product."
    )
    Quantity: int = Field(description="Quantity of the product.")
    SalesorderId: int | None = Field(
        None,
        description='The Id for the Salesorder. Note that if the barcode was from a "Prepack" label, this will not be populated.',
    )
    InvoiceId: int | None = Field(
        None,
        description='The Id for the invoice. Note that if the barcode was from a "Prepack" label, this will not be populated.',
    )
    PurchaseOrder: str | None = Field(
        None,
        description='Customer PurchaseOrder (custom notes or identifier) on the order. Note that if the barcode was from a "Prepack" label, this will not be populated.',
    )
    CountryOfOrigin: str | None = Field(
        None, description="The country that the product originates from."
    )
    LotCode: str | None = Field(None, description="The Lot Code")
    DateCode: str | None = Field(None, description="The date code")


class PackListDetail(BaseModel):
    DigiKeyPartNumber: str = Field(description="The Digi-Key part number.")
    Quantity: int = Field(description="Quantity of the product.")


class PackListBarcodeResponse(BaseModel):
    SalesorderId: int = Field(description="The Id for the Salesorder.")
    InvoiceId: int = Field(description="The Id for the invoice.")
    PackListNumber: int = Field(description="PackList number.")
    PackListDetails: list[PackListDetail] = Field(
        description="List of PackList Details."
    )
