# generated by datamodel-codegen:
#   filename:  PackList_oas3.yaml
#   timestamp: 2024-10-17T06:20:22+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class DKProblemDetails(BaseModel):

    type: Optional[str] = Field(None)
    title: Optional[str] = Field(None)
    status: Optional[int] = Field(None)
    detail: Optional[str] = Field(None)
    instance: Optional[str] = Field(None)
    correlationId: Optional[str] = Field(None)
    errors: Optional[Dict[str, List[str]]] = Field(None)


class PackingListItemT(BaseModel):

    InvoiceId: Optional[int] = Field(
        None, description="Invoice ID of order. There is one per shipment."
    )
    SalesOrderId: Optional[int] = Field(
        None, description="Sales order ID. There is one per order."
    )
    PurchaseOrderNumber: Optional[int] = Field(
        None,
        description="Purchase Order Number supplied by the customer when the order was placed.",
    )
    OrderedQuantity: Optional[int] = Field(
        None,
        description="Number of items ordered of products included in the packing list for given line item",
    )
    QuantityShipped: Optional[int] = Field(
        None, description="The quantity of items in the shipment"
    )
    QuantityBackOrder: Optional[int] = Field(
        None, description="The quantity of items on backorder"
    )
    CustomerLineItemId: Optional[str] = Field(None, description="Customer Line item id")
    LineItem: Optional[str] = Field(
        None, description="DigiKey’s Line Item number for that Sales Order"
    )
    ProductNumber: Optional[str] = Field(
        None, description="DigiKey product number for given line item"
    )
    Description: Optional[str] = Field(
        None, description="Product Description\u202ffor given line item"
    )
    ECCN: Optional[str] = Field(
        None,
        description="Export control class number for given line item. See documentation from the U.S. Department of Commerce.",
    )
    CustomerPartNumber: Optional[str] = Field(
        None, description="Customer Part Number\u202ffor given line item"
    )
    HTSUS: Optional[str] = Field(
        None,
        description="Harmonized Tariff Schedule of the United States\u202ffor given line item. See documentation from the U.S. International Trade Commission.",
    )
    ManufacturerProductNumber: Optional[str] = Field(
        None, description="Manufacturer part number for given line item"
    )
    Manufacturer: Optional[str] = Field(
        None, description="Manufacturer Name\u202ffor given line item"
    )
    CountryOfOrigin: Optional[str] = Field(
        None, description="Country of origin for given line item"
    )
    LotQuantity: Optional[int] = Field(
        None, description="Quantity of products in the lot for given line item"
    )
    DateCode: Optional[str] = Field(
        None, description="Date Code for given line item. Format is MMM-YYYY"
    )
    LotCode: Optional[str] = Field(
        None, description="Lot Code\u202ffor given line item"
    )


class InvoicePackingList(BaseModel):

    PackingListItem: Optional[List[PackingListItemT]] = Field(
        None, description="Item found from Invoice"
    )
    InvoiceIdEntered: Optional[int] = Field(
        None, description="The InvoiceID that you entered in the request"
    )
    IncludePdfEntered: Optional[bool] = Field(
        None,
        description='The value that you entered in the request. "True" is to return the encoded pdf string. "False" is to not.',
    )
    PdfFound: Optional[bool] = Field(
        None, description="Pdf for this invoice has been found"
    )
    EncodedString: Optional[str] = Field(
        None, description="Enter this string in a string decoder to generate a pdf."
    )


class SalesOrderPackList(BaseModel):

    PackingListInvoice: Optional[List[InvoicePackingList]] = Field(
        None, description="Invoices from the sales order id provided"
    )
    SalesOrderIdEntered: Optional[int] = Field(
        None, description="The SalesOrderID that you entered in the reques"
    )
