# generated by datamodel-codegen:
#   filename:  ProductSearch_oas3.yaml
#   timestamp: 2024-10-16T04:56:22+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field

Field_alias = Field


class BaseFilterV4(BaseModel):

    Id: Optional[int] = Field(None)
    Value: Optional[str] = Field(None)
    ProductCount: Optional[int] = Field(None)


class BaseProduct(BaseModel):

    Id: Optional[int] = Field(None, description="Manufacturer Id")
    Name: Optional[str] = Field(None, description="Manufacturer Name")


class CategoryT(BaseModel):

    CategoryId: Optional[int] = Field(None, description="CategoryId")
    ParentId: Optional[int] = Field(
        None,
        description="The Id of the Parent Category if the given category is a child of another category",
    )
    Name: Optional[str] = Field(None, description="Category Name")
    ProductCount: Optional[int] = Field(
        None, description="Number of Products in the Category"
    )
    Children: Optional[List[CategoryT]] = Field(
        None, description="List of Child Categories"
    )


class CategoryNode(BaseModel):

    CategoryId: Optional[int] = Field(None, description="The Category Id")
    ParentId: Optional[int] = Field(
        None,
        description="If this is a child category, this is the Id of the parent category",
    )
    Name: Optional[str] = Field(None, description="Category name")
    ProductCount: Optional[int] = Field(
        None, description="The number of products in the category"
    )
    NewProductCount: Optional[int] = Field(
        None, description="The number of new products in the category"
    )
    ImageUrl: Optional[str] = Field(
        None, description="The URL of the image of the category"
    )
    SeoDescription: Optional[str] = Field(
        None, description="The SEO description for the category"
    )
    ChildCategories: Optional[List[CategoryNode]] = Field(
        None,
        description="A list of all children of the category - Their parent Id will be Category Id",
    )


class CategoryType(BaseModel):

    CategoryId: Optional[int] = Field(
        None, description="ID for DigiKey product category"
    )
    Level: Optional[int] = Field(None, description="DigiKey Product Category level")
    Name: Optional[str] = Field(None, description="Name of DigiKey product category")


class ClassificationsT(BaseModel):

    ReachStatus: Optional[str] = Field(None, description="ReachStatus")
    RohsStatus: Optional[str] = Field(None, description="RohsStatus")
    MoistureSensitivityLevel: Optional[str] = Field(
        None, description="Code for Moisture Sensitivity Level of the product"
    )
    ExportControlClassNumber: Optional[str] = Field(
        None,
        description="Export control class number. See documentation from the U.S. Department of Commerce.",
    )
    HtsusCode: Optional[str] = Field(
        None,
        description="Harmonized Tariff Schedule of the United States. See documentation from the U.S. International Trade Commission.",
    )


class DKProblemDetails(BaseModel):

    type: Optional[str] = Field(None)
    title: Optional[str] = Field(None)
    status: Optional[int] = Field(None)
    detail: Optional[str] = Field(None)
    instance: Optional[str] = Field(None)
    correlationId: Optional[str] = Field(None)
    errors: Optional[Dict[str, List[str]]] = Field(None)


class DescriptionT(BaseModel):

    ProductDescription: Optional[str] = Field(
        None,
        description="Description of the product. If you entered a valid Locale and Language in the input, we will return the description in that language. Otherwise, we’ll return the English description.",
    )
    DetailedDescription: Optional[str] = Field(
        None,
        description="Detailed description of the product. If you entered a valid Locale and Language in the input, we will return the description in that language. Otherwise, we’ll return the English description.",
    )


class FilterId(BaseModel):

    Id: Optional[str] = Field(None, description="The Id of the Filter")


class MarketPlaceFilterT(Enum):
    NoFilter = "NoFilter"
    ExcludeMarketPlace = "ExcludeMarketPlace"
    MarketPlaceOnly = "MarketPlaceOnly"


class SearchOption(Enum):
    ChipOutpost = "ChipOutpost"
    Has3DModel = "Has3DModel"
    HasCadModel = "HasCadModel"
    HasDatasheet = "HasDatasheet"
    HasProductPhoto = "HasProductPhoto"
    InStock = "InStock"
    NewProduct = "NewProduct"
    NonRohsCompliant = "NonRohsCompliant"
    NormallyStocking = "NormallyStocking"
    RohsCompliant = "RohsCompliant"


class RangeFilterTypeT(Enum):
    Min = "Min"
    Max = "Max"
    Range = "Range"


class FilterValue(BaseModel):

    ProductCount: Optional[int] = Field(
        None, description="Number of products with this filter"
    )
    ValueId: Optional[str] = Field(None, description="Filter Value Id")
    ValueName: Optional[str] = Field(None, description="Filter Value Name")
    RangeFilterType: Optional[RangeFilterTypeT] = Field(
        None, description="Filter Range - possible values: Min, Max, Range"
    )


class FiltersT(BaseModel):

    IsInStock: Optional[bool] = Field(
        None, description="Did we use the “IsInStock” limit?", examples=[False]
    )
    ExcludeMarketplace: Optional[bool] = Field(
        None, description="Did we use the “ExcludeMarketplace” limit?", examples=[False]
    )


class IsoSearchLocale(BaseModel):

    Site: Optional[str] = Field(
        None,
        description="The site we used for the API call. Note this may be different than the value you entered if that value was not one of our allowed values.",
        examples=["US"],
    )
    Language: Optional[str] = Field(
        None,
        description="The language we used for the API call. Note this may be different than the value you entered if that value was not one of our allowed values or not valid for the entered site.",
        examples=["en"],
    )
    Currency: Optional[str] = Field(
        None,
        description="The currency we used for the API call. Note this may be different than the value you entered if that value was not one of our allowed values or not valid for the entered site.",
        examples=["USD"],
    )


class ManufacturerT(BaseModel):

    Id: Optional[int] = Field(None, description="Manufacturer Id")
    Name: Optional[str] = Field(None, description="Manufacturer Name")


class ManufacturerInfo(BaseModel):

    Id: Optional[int] = Field(None, description="Manufacturer Id")
    Name: Optional[str] = Field(None, description="Manufacturer Name")


class ManufacturersResponse(BaseModel):

    Manufacturers: Optional[List[ManufacturerInfo]] = Field(
        None, description="List of Manufacturer Information"
    )


class MediaLinksT(BaseModel):

    MediaType: Optional[str] = Field(None, description="The type of media.")
    Title: Optional[str] = Field(None, description="The title of the media.")
    SmallPhoto: Optional[str] = Field(None, description="URL to a small photo.")
    Thumbnail: Optional[str] = Field(
        None, description="URL to the thumbnail image of the media."
    )
    Url: Optional[str] = Field(None, description="URL of the media.")


class MediaResponse(BaseModel):

    MediaLinks: Optional[List[MediaLinksT]] = Field(
        None, description="List of Media Links"
    )


class PackageTypeT(BaseModel):

    Id: Optional[int] = Field(None, description="PackageType Id")
    Name: Optional[str] = Field(None, description="PackageType Name")


class Parameter(BaseModel):

    Id: Optional[int] = Field(None, description="Parameter Id")
    Text: Optional[str] = Field(None, description="Parameter Description")
    Priority: Optional[int] = Field(None, description="Parameter priority")


class ParameterFilterOptionsResponse(BaseModel):

    Category: Optional[BaseFilterV4] = Field(None)
    ParameterType: Optional[str] = Field(None, description="Parameter Type")
    ParameterId: Optional[int] = Field(None, description="Parameter Id")
    ParameterName: Optional[str] = Field(None, description="Parameter Name")
    FilterValues: Optional[List[FilterValue]] = Field(
        None, description="List of Filter Values for the Parameter"
    )


class ParameterTypeT(Enum):
    String = "String"
    Integer = "Integer"
    Double = "Double"
    UnitOfMeasure = "UnitOfMeasure"
    CoupledUnitOfMeasure = "CoupledUnitOfMeasure"
    RangeUnitOfMeasure = "RangeUnitOfMeasure"


class ParameterValue(BaseModel):

    ParameterId: Optional[int] = Field(None, description="Parameter Id")
    ParameterText: Optional[str] = Field(None, description="Parameter Text")
    ParameterType: Optional[ParameterTypeT] = Field(
        None, description="Parameter Data Type"
    )
    ValueId: Optional[str] = Field(None, description="The Id of the Parameter value")
    ValueText: Optional[str] = Field(
        None, description="The text of the Parameter value"
    )


class ParametricCategory(BaseModel):

    ParameterId: Optional[int] = Field(None, description="Parameter Id")
    FilterValues: Optional[List[FilterId]] = Field(
        None, description="List of FilterIdDtos"
    )


class PriceBreak(BaseModel):

    BreakQuantity: Optional[int] = Field(
        None, description="The quantity at which the price takes effect"
    )
    UnitPrice: Optional[float] = Field(
        None, description="The unit price for the quantity"
    )
    TotalPrice: Optional[float] = Field(None, description="The total price")


class ProductPricingVariation(BaseModel):

    DigiKeyProductNumber: Optional[str] = Field(
        None, description="DigiKey Product number of the variation"
    )
    QuantityAvailableforPackageType: Optional[int] = Field(
        None, description="The quantity available for the specified variation."
    )
    PackageType: Optional[PackageTypeT] = Field(None)
    MarketPlace: Optional[bool] = Field(
        None,
        description="Product is a Marketplace product that ships direct from the supplier. A separate shipping fee may apply",
    )
    StandardPricing: Optional[List[PriceBreak]] = Field(
        None, description="Standard pricing for the validated locale."
    )
    MyPricing: Optional[List[PriceBreak]] = Field(
        None,
        description="Your pricing for the DigiKey customer number with which you authenticated. Also dependent on locale information.",
    )
    IsTariffActive: Optional[bool] = Field(
        None, description="Indicates if tariff is active for variation"
    )
    DigiReelingFee: Optional[float] = Field(
        None, description="Reeling fee per product ordered"
    )


class ProductStatusV4(BaseModel):

    Id: Optional[int] = Field(None)
    Status: Optional[str] = Field(None)


class ProductSubstitute(BaseModel):

    SubstituteType: Optional[str] = Field(None, description="Substitute type")
    ProductUrl: Optional[str] = Field(None, description="Product url")
    Description: Optional[str] = Field(None, description="Product Description")
    Manufacturer: Optional[ManufacturerT] = Field(None)
    ManufacturerProductNumber: Optional[str] = Field(
        None, description="Manufacturer Product Number"
    )
    UnitPrice: Optional[str] = Field(None, description="Unit Price")
    QuantityAvailable: Optional[int] = Field(None, description="Quantity Available")


class ProductSubstitutesResponse(BaseModel):

    ProductSubstitutesCount: Optional[int] = Field(
        None, description="Count of ProductSubstitutes"
    )
    ProductSubstitutes: Optional[List[ProductSubstitute]] = Field(
        None, description="List of ProductSubstitutes"
    )
    SearchLocaleUsed: Optional[IsoSearchLocale] = Field(None)


class ProductSummary(BaseModel):

    ProductUrl: Optional[str] = Field(None, description="Product url")
    Description: Optional[str] = Field(None, description="Product Description")
    Manufacturer: Optional[ManufacturerT] = Field(None)
    ManufacturerProductNumber: Optional[str] = Field(
        None, description="Manufacturer Product Number"
    )
    UnitPrice: Optional[str] = Field(None, description="Unit Price")
    QuantityAvailable: Optional[int] = Field(None, description="Quantity Available")


class RecommendedProduct(BaseModel):

    DigiKeyProductNumber: Optional[str] = Field(
        None, description="The Digi-Key part number."
    )
    ManufacturerProductNumber: Optional[str] = Field(
        None, description="The manufacturer part number."
    )
    ManufacturerName: Optional[str] = Field(
        None, description="The name of the manufacturer."
    )
    PrimaryPhoto: Optional[str] = Field(
        None, description="The URL to the product’s image."
    )
    ProductDescription: Optional[str] = Field(
        None, description="Catalog description of the product."
    )
    QuantityAvailable: Optional[int] = Field(
        None,
        description="Quantity of the product available for immediate sale.",
        examples=[54],
    )
    UnitPrice: Optional[float] = Field(
        None,
        description="The catalog price for a single unit of this product.",
        examples=[94.95],
    )
    ProductUrl: Optional[str] = Field(
        None,
        description="URL of the Digi-Key catalog page to purchase the product. This is based on your provided header Locale values.",
    )


class SeriesT(BaseModel):

    Id: Optional[int] = Field(None, description="Series Id")
    Name: Optional[str] = Field(None, description="Series Name")


class SettingsUsedT(BaseModel):

    CustomerId: Optional[int] = Field(
        None, description="The CustomerId that was used for the search and pricing"
    )
    SearchLocale: Optional[IsoSearchLocale] = Field(None)
    Filters: Optional[FiltersT] = Field(None)


class FieldModel(Enum):
    None_ = "None"
    Packaging = "Packaging"
    ProductStatus = "ProductStatus"
    DigiKeyProductNumber = "DigiKeyProductNumber"
    ManufacturerProductNumber = "ManufacturerProductNumber"
    Manufacturer = "Manufacturer"
    MinimumQuantity = "MinimumQuantity"
    QuantityAvailable = "QuantityAvailable"
    Price = "Price"
    Supplier = "Supplier"
    PriceManufacturerStandardPackage = "PriceManufacturerStandardPackage"


class SortOrderT(Enum):
    Ascending = "Ascending"
    Descending = "Descending"


class SortOptionsT(BaseModel):

    Field: Optional[FieldModel] = Field_alias(
        None, description="Field in response to sort by"
    )
    SortOrder: Optional[SortOrderT] = Field_alias(
        None, description="Direction to sort by Ascending or Descending"
    )


class SupplierT(BaseModel):

    Id: Optional[int] = Field(None, description="Supplier Id")
    Name: Optional[str] = Field(None, description="Supplier Name")


class TopCategoryNode(BaseModel):

    Id: Optional[int] = Field(None, description="Category Id")
    Name: Optional[str] = Field(None, description="Category Name")
    ProductCount: Optional[int] = Field(
        None, description="Product count for the Category"
    )


class AlternatePackaging(BaseModel):

    AlternatePackaging: Optional[List[ProductSummary]] = Field(
        None, description="Alternate packaging options for this product"
    )


class AlternatePackagingResponse(BaseModel):

    AlternatePackagings: Optional[AlternatePackaging] = Field(None)
    SearchLocaleUsed: Optional[IsoSearchLocale] = Field(None)


class CategoriesResponse(BaseModel):

    ProductCount: Optional[int] = Field(None, description="Count of Products")
    Categories: Optional[List[CategoryT]] = Field(
        None, description="List of Categories"
    )
    SearchLocaleUsed: Optional[IsoSearchLocale] = Field(None)


class CategoryResponse(BaseModel):

    Category: Optional[CategoryT] = Field(None)
    SearchLocaleUsed: Optional[IsoSearchLocale] = Field(None)


class DigiReelPricing(BaseModel):

    ReelingFee: Optional[float] = Field(
        None, description="Fee per reel ordered.", examples=[7.0]
    )
    UnitPrice: Optional[float] = Field(
        None, description="Price of a single unit of the product.", examples=[0.01704]
    )
    ExtendedPrice: Optional[float] = Field(
        None,
        description="The total price of the requested reels and the reeling fee.",
        examples=[8.52],
    )
    RequestedQuantity: Optional[int] = Field(
        None,
        description="The passed in quantity of the product you are looking to create a Digi-Reel with.",
        examples=[500],
    )
    SearchLocaleUsed: Optional[IsoSearchLocale] = Field(None)


class PackageTypeByQuantityProduct(BaseModel):

    RecommendedQuantity: Optional[int] = Field(
        None, description="Recommended quantity for product"
    )
    DigiKeyProductNumber: Optional[str] = Field(
        None, description="The Digi-Key part number.", examples=["36-117-ND"]
    )
    QuantityAvailable: Optional[int] = Field(
        None, description="Quantity of the product available for immediate sale."
    )
    ProductDescription: Optional[str] = Field(
        None, description="Catalog description of the product."
    )
    DetailedDescription: Optional[str] = Field(
        None, description="Extended catalog description of the product."
    )
    ManufacturerName: Optional[str] = Field(
        None, description="Manufacturer of the product."
    )
    ManufacturerProductNumber: Optional[str] = Field(
        None,
        description="The manufacturer part number. Note that some manufacturer part numbers may be used by multiple manufacturers for\r\ndifferent parts.",
    )
    MinimumOrderQuantity: Optional[int] = Field(
        None, description="The minimum quantity to order from Digi-Key."
    )
    PrimaryDatasheetUrl: Optional[str] = Field(
        None, description="The URL to the product's datasheet."
    )
    PrimaryPhotoUrl: Optional[str] = Field(
        None, description="The URL to the product's image."
    )
    ProductStatus: Optional[str] = Field(
        None,
        description="Status of the product. Options include: Active, Obsolete, Discontinued at Digi-Key,\r\nLast Time Buy, Not For New Designs, Preliminary. For obsolete parts the part\r\nwill become a non-stocking item when stock is depleted; minimums will apply.\r\nOrder the quantity available or the quantity available plus a multiple of the\r\nminimum order quantity.\r\n///",
    )
    ManufacturerLeadWeeks: Optional[str] = Field(
        None,
        description="The number of weeks expected to receive stock from manufacturer.",
        examples=["6 weeks"],
    )
    ManufacturerWarehouseQuantity: Optional[int] = Field(
        None,
        description="Quantity of this product available to order from manufacturer.",
        examples=[165000],
    )
    RohsStatus: Optional[str] = Field(
        None,
        description="RoHS status. Can be RoHS Compliant, RoHS non-compliant, RoHS Compliant By Exemption, Not Applicable, Vendor\r\nundefined, Request Inventory Verification, or ROHS3 Compliant.",
        examples=["RoHS Compliant"],
    )
    RoHSCompliant: Optional[bool] = Field(
        None, description="Boolean value for RoHS compliance."
    )
    QuantityOnOrder: Optional[int] = Field(
        None,
        description="Quantity of this product ordered but not immediately available.",
        examples=[0],
    )
    StandardPricing: Optional[List[PriceBreak]] = Field(
        None, description="Standard pricing for the validated locale."
    )
    MyPricing: Optional[List[PriceBreak]] = Field(
        None, description="My pricing for the validated locale."
    )
    ProductUrl: Optional[str] = Field(
        None,
        description="Full URL of the Digi-Key catalog page to purchase the product. This is based on your provided Locale values.",
        examples=[
            "https://www.digikey.com/product-detail/en/keystone-electronics/117/36-117-ND/7385294"
        ],
    )
    MarketPlace: Optional[bool] = Field(
        None, description="Is this product a marketplace product"
    )
    Supplier: Optional[str] = Field(None, description="Name of product supplier")
    StockNote: Optional[str] = Field(
        None,
        description="Description of Digi-Key's current stocking status for the product. Possible values include: In Stock, Temporarily\r\nOut of Stock, and Limited Supply - Call.",
        examples=["In Stock"],
    )
    PackageTypes: Optional[List[str]] = Field(None)


class PackageTypeByQuantityResponse(BaseModel):

    Products: Optional[List[PackageTypeByQuantityProduct]] = Field(
        None,
        description="List of products that matched the PackageTypeByQuantitySearchService request.",
    )


class ParameterFilterRequestT(BaseModel):

    CategoryFilter: Optional[FilterId] = Field(None)
    ParameterFilters: Optional[List[ParametricCategory]] = Field(
        None, description="The list of search parameters"
    )


class ProductAssociationsT(BaseModel):

    Kits: Optional[List[ProductSummary]] = Field(
        None, description="Kits that this product is contained in."
    )
    MatingProducts: Optional[List[ProductSummary]] = Field(
        None,
        description="An association of same manufacturer products that mate with each other.",
    )
    AssociatedProducts: Optional[List[ProductSummary]] = Field(
        None,
        description="Products that are directly correlated to complete the intended function of the product. These products may be either same manufacturer or differ.",
    )
    ForUseWithProducts: Optional[List[ProductSummary]] = Field(
        None,
        description="Products that are directly correlated to complete the intended function of th product. These products may be either same manufacturer or differ.",
    )


class ProductAssociationsResponse(BaseModel):

    ProductAssociations: Optional[ProductAssociationsT] = Field(None)
    SearchLocaleUsed: Optional[IsoSearchLocale] = Field(None)


class ProductPricing(BaseModel):

    ManufacturerProductNumber: Optional[str] = Field(
        None,
        description="The manufacturer part number. Note that some manufacturer part numbers may be used by multiple manufacturers for different parts.",
    )
    Manufacturer: Optional[ManufacturerT] = Field(None)
    Description: Optional[DescriptionT] = Field(None)
    QuantityAvailable: Optional[int] = Field(
        None, description="In-stock quantity that is available for immediate shipping."
    )
    ProductUrl: Optional[str] = Field(
        None,
        description="Full URL of the Digi-Key catalog page to purchase the product. This is based on your provided Locale values.",
        examples=[
            "https://www.digikey.com/product-detail/en/keystone-electronics/117/36-117-ND/7385294"
        ],
    )
    IsDiscontinued: Optional[bool] = Field(
        None,
        description="This product is no longer sold at DigiKey and will no longer be restocked.",
    )
    NormallyStocking: Optional[bool] = Field(
        None, description="Indicates if a product is normally stocked."
    )
    IsObsolete: Optional[bool] = Field(None, description="Product is obsolete")
    ManufacturerLeadWeeks: Optional[str] = Field(
        None,
        description="The number of weeks expected to receive stock from manufacturer to DigiKey.",
    )
    ManufacturerPublicQuantity: Optional[int] = Field(
        None,
        description="The manufacturer’s factory stock that can be ordered and will ship once DigiKey receives it from the manufacturer.",
    )
    StandardPackage: Optional[int] = Field(
        None,
        description="The number of products in the manufacturer's standard package.",
    )
    ExportControlClassNumber: Optional[str] = Field(
        None,
        description="Export control class number. See documentation from the U.S. Department of Commerce.",
    )
    HtsusCode: Optional[str] = Field(
        None,
        description="Harmonized Tariff Schedule of the United States. See documentation from the U.S. International Trade Commission.",
    )
    MoistureSensitivityLevel: Optional[str] = Field(
        None, description="Code for Moisture Sensitivity Level of the product"
    )
    IsBoNotAllowed: Optional[bool] = Field(
        None,
        description="Is Back Order not allowed? True if you cannot place a backorder; false if we will allow the product to be back-ordered.",
    )
    IsNcnr: Optional[bool] = Field(
        None, description="Is product non-cancellable and non-returnable"
    )
    Categories: Optional[List[CategoryType]] = Field(
        None,
        description="The main category that the part is in(this does not include sub categories)",
    )
    ContainsLithium: Optional[bool] = Field(
        None, description="Indicates if product contains lithium"
    )
    ContainsMercury: Optional[bool] = Field(
        None, description="Indicates if product contains mercury"
    )
    IsEndOfLife: Optional[bool] = Field(
        None,
        description="This product is no longer manufactured and will no longer be stocked once stock is depleted.",
    )
    ProductVariations: Optional[List[ProductPricingVariation]] = Field(
        None, description="Variations of the requested ProductPricing"
    )


class ProductPricingResponse(BaseModel):

    ProductPricings: Optional[List[ProductPricing]] = Field(
        None, description="List of Products"
    )
    ProductsCount: Optional[int] = Field(
        None, description="Total number of matching products found.", examples=[6463]
    )
    SettingsUsed: Optional[SettingsUsedT] = Field(None)


class ProductVariation(BaseModel):

    DigiKeyProductNumber: Optional[str] = Field(
        None, description="DigiKey Product number of the variation"
    )
    PackageType: Optional[PackageTypeT] = Field(None)
    StandardPricing: Optional[List[PriceBreak]] = Field(
        None, description="Standard pricing for the validated locale."
    )
    MyPricing: Optional[List[PriceBreak]] = Field(
        None,
        description="Your pricing for the account with which you authenticated. Also dependent on locale information.",
    )
    MarketPlace: Optional[bool] = Field(
        None,
        description="Product is a Marketplace product that ships direct from the supplier. A separate shipping fee may apply",
    )
    TariffActive: Optional[bool] = Field(
        None, description="Indicates if there is a tariff on the item."
    )
    Supplier: Optional[SupplierT] = Field(None)
    QuantityAvailableforPackageType: Optional[int] = Field(
        None, description="The quantity available for the specified variation."
    )
    MaxQuantityForDistribution: Optional[int] = Field(
        None, description="Maximum order quantity for Distribution"
    )
    MinimumOrderQuantity: Optional[int] = Field(
        None, description="The Minimum Order Quantity"
    )
    StandardPackage: Optional[int] = Field(
        None,
        description="The number of products in the manufacturer's standard package.",
    )
    DigiReelFee: Optional[float] = Field(None, description="Fee per reel ordered.")


class Recommendation(BaseModel):

    ProductNumber: Optional[str] = Field(
        None, description="The product number that the recommendations are for."
    )
    RecommendedProducts: Optional[List[RecommendedProduct]] = Field(
        None, description="The list of recommended products."
    )
    SearchLocaleUsed: Optional[IsoSearchLocale] = Field(None)


class RecommendedProductsResponse(BaseModel):

    Recommendations: Optional[List[Recommendation]] = Field(
        None,
        description="The list of RecommendedProductsCollections - each containing a Product and its recommendations.",
    )


class TopCategory(BaseModel):

    RootCategory: Optional[TopCategoryNode] = Field(None)
    Category: Optional[TopCategoryNode] = Field(None)
    Score: Optional[float] = Field(None, description="Category Score")
    ImageUrl: Optional[str] = Field(None, description="URL for the Category image")


class FilterOptionsT(BaseModel):

    Manufacturers: Optional[List[BaseFilterV4]] = Field(
        None,
        description="The Manufacturers that can be filtered to narrow next search request",
    )
    Packaging: Optional[List[BaseFilterV4]] = Field(
        None, description="Packaging that can be filtered to narrow next search request"
    )
    Status: Optional[List[BaseFilterV4]] = Field(
        None, description="Status that can be filtered to narrow next search request"
    )
    Series: Optional[List[BaseFilterV4]] = Field(
        None, description="Series that can be filtered to narrow next search request"
    )
    ParametricFilters: Optional[List[ParameterFilterOptionsResponse]] = Field(
        None,
        description="ParaetricFilter that can be filtered to narrow next search request",
    )
    TopCategories: Optional[List[TopCategory]] = Field(
        None, description="the top Categories to filter"
    )
    MarketPlaceFilters: Optional[List[MarketPlaceFilterT]] = Field(
        None, description="Marketplace Filter"
    )


class FilterOptionsRequestT(BaseModel):

    ManufacturerFilter: Optional[List[FilterId]] = Field(
        None, description="Filter on Manufacturer"
    )
    CategoryFilter: Optional[List[FilterId]] = Field(None, description="Category")
    StatusFilter: Optional[List[FilterId]] = Field(None, description="Status")
    PackagingFilter: Optional[List[FilterId]] = Field(None, description="Packaging")
    MarketPlaceFilter: Optional[MarketPlaceFilterT] = Field(
        None, description="MarketPlaceFilter"
    )
    SeriesFilter: Optional[List[FilterId]] = Field(None, description="SeriesFilter")
    MinimumQuantityAvailable: Optional[int] = Field(
        None, description="The MinimumQuantityAvailable for the result to display"
    )
    ParameterFilterRequest: Optional[ParameterFilterRequestT] = Field(None)
    SearchOptions: Optional[List[SearchOption]] = Field(
        None, description="/SearchOptions"
    )


class KeywordRequest(BaseModel):

    Keywords: Optional[str] = Field(
        None, description="A String of Keywords, up to 250 characters"
    )
    Limit: Optional[int] = Field(
        None, description="Number of products to return between 1 and 50."
    )
    Offset: Optional[int] = Field(
        None,
        description="The starting index of the records returned. This is used to paginate beyond RecordCount number of results.",
    )
    FilterOptionsRequest: Optional[FilterOptionsRequestT] = Field(None)
    SortOptions: Optional[SortOptionsT] = Field(None)


class ProductT(BaseModel):

    Description: Optional[DescriptionT] = Field(None)
    Manufacturer: Optional[ManufacturerT] = Field(None)
    ManufacturerProductNumber: Optional[str] = Field(
        None,
        description="The manufacturer part number. Note that some manufacturer part numbers may be used by multiple manufacturers for different parts.",
    )
    UnitPrice: Optional[float] = Field(
        None, description="The price for a single unit of this product."
    )
    ProductUrl: Optional[str] = Field(
        None,
        description="Full URL of the Digi-Key catalog page to purchase the product. This is based on your provided Locale values.",
        examples=[
            "https://www.digikey.com/product-detail/en/keystone-electronics/117/36-117-ND/7385294"
        ],
    )
    DatasheetUrl: Optional[str] = Field(
        None, description="The URL to the product's datasheet."
    )
    PhotoUrl: Optional[str] = Field(None, description="The URL to the product's image.")
    ProductVariations: Optional[List[ProductVariation]] = Field(None)
    QuantityAvailable: Optional[int] = Field(
        None,
        description="The sum of the quantity for all package types that are found in ProductVariations.",
    )
    ProductStatus: Optional[ProductStatusV4] = Field(None)
    BackOrderNotAllowed: Optional[bool] = Field(
        None, description="True if back order is not allowed for this product"
    )
    NormallyStocking: Optional[bool] = Field(
        None, description="Indicates if a product is normally stocked."
    )
    Discontinued: Optional[bool] = Field(
        None,
        description="This product is no longer sold at Digi-Key and will no longer be stocked.",
    )
    EndOfLife: Optional[bool] = Field(
        None,
        description="This product is no longer manufactured and will no longer be stocked once stock is depleted.",
    )
    Ncnr: Optional[bool] = Field(
        None, description="Is product non-cancellable and non-returnable"
    )
    PrimaryVideoUrl: Optional[str] = Field(
        None, description="The URL to the product's video"
    )
    Parameters: Optional[List[ParameterValue]] = Field(None)
    BaseProductNumber: Optional[BaseProduct] = Field(None)
    Category: Optional[CategoryNode] = Field(None)
    DateLastBuyChance: Optional[datetime] = Field(
        None,
        description="Last date that the product will be available for purchase. Date is in ISO 8601.",
    )
    ManufacturerLeadWeeks: Optional[str] = Field(
        None,
        description="The number of weeks expected to receive stock from manufacturer.",
    )
    ManufacturerPublicQuantity: Optional[int] = Field(
        None,
        description="Quantity of this product available to order from manufacturer.",
    )
    Series: Optional[SeriesT] = Field(None)
    ShippingInfo: Optional[str] = Field(
        None, description="Additional shipping information - if available"
    )
    Classifications: Optional[ClassificationsT] = Field(None)


class ProductDetails(BaseModel):

    SearchLocaleUsed: Optional[IsoSearchLocale] = Field(None)
    Product: Optional[ProductT] = Field(None)


class KeywordResponse(BaseModel):

    Products: Optional[List[ProductT]] = Field(None)
    ProductsCount: Optional[int] = Field(
        None, description="Total number of matching products found.", examples=[6463]
    )
    ExactMatches: Optional[List[ProductT]] = Field(None)
    FilterOptions: Optional[FilterOptionsT] = Field(None)
    SearchLocaleUsed: Optional[IsoSearchLocale] = Field(None)
    AppliedParametricFiltersDto: Optional[List[Parameter]] = Field(None)


CategoryT.update_forward_refs()  # type: ignore
CategoryNode.update_forward_refs()  # type: ignore
